core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clientes/', include('clientes.urls')),
    path('servicos/', include('servicos.urls')),
    path('login/', include('autenticacao.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

servicos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from servicos import views

urlpatterns = [
    path('novo_servico/', login_required(views.novo_servico, login_url='/login/'), name='novo_servico'),
    path('seleciona_servico/', login_required(views.editar_servico, login_url='/login/'), name='editar_servico'),
    path('editar_servico/', login_required(views.seleciona_servico, login_url='/login/'), name='seleciona_servico'),
    path('listar_servicos/', login_required(views.listar_servico, login_url='/login/'), name='listar_servico'),
    path('protocolo/<str:protocolo>', login_required(views.protocolo, login_url='/login/'), name='servico'),
    path('alterar_servico/<int:servico_id>', login_required(views.alterar_servico, login_url='/login/'), name='alterar_servico'),
    path("carros-por-cliente/<int:cliente_id>/", login_required(views.carros_por_cliente, login_url='/login/'), name="carros_por_cliente"),
]

servicos/models.py
from django.db import models
from secrets import token_hex
from datetime import datetime
from clientes.models import Cliente, Carro
from .categorias import ChoicesCategoriaManutencao
from babel.numbers import format_currency

# class CategoriaManutencao(models.Model):
#     titulo = models.CharField(max_length=100, choices=ChoicesCategoriaManutencao.choices)
#     preco = models.DecimalField(max_digits=7, decimal_places=2)

#     def __str__(self):
#         return self.titulo

class CategoriaManutencao(models.Model):
    titulo = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.titulo

class Servicos(models.Model):
    titulo = models.CharField(max_length=50)
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True)
    carro = models.ForeignKey(Carro, on_delete=models.SET_NULL, null=True, blank=True)
    categoria_manutencao = models.ManyToManyField(
        CategoriaManutencao, through='ServicoCategoriaQuantidade'
    )
    mecanico_resp = models.CharField(max_length=100, blank=True, null=True, default='-')
    data_inicio = models.DateField(null=True)
    data_entrega = models.DateField(null=True)
    status = models.CharField(max_length=25, default='Em Orçamento')
    data_finalizacao = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    notifica_cliente = models.BooleanField(max_length=5, default=True)
    protocolo = models.CharField(max_length=18, null=True, blank=True, unique=True)

    def __str__(self):
        return f"{self.titulo} | {self.cliente}"

    def save(self, *args, **kwargs):
        if not self.protocolo:
            self.protocolo = datetime.now().strftime('%d%m%Y%H%M%S') + token_hex(2)

        if self.status == 'Finalizado':
            self.data_finalizacao = datetime.now()
            
        super(Servicos, self).save(*args, **kwargs)

    def preco_total(self):
        preco_total = 0.0
        for item in self.servicocategoriaquantidade_set.all():
            preco_total += float(item.categoria.preco) * item.quantidade + float(item.valor_mao_de_obra)
        
        # Formata o valor usando o Babel para moeda brasileira
        return format_currency(preco_total, 'BRL', locale='pt_BR')


class ServicoCategoriaQuantidade(models.Model):
    servico = models.ForeignKey(Servicos, on_delete=models.CASCADE)
    categoria = models.ForeignKey(CategoriaManutencao, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)
    valor_mao_de_obra = models.DecimalField(max_digits=7, decimal_places=2, default=0)


    def __str__(self):
        return f"{self.servico.titulo} - {self.categoria.titulo} (Quantidade: {self.quantidade})"

servicos/forms.py
from django.forms import ModelForm
from .models import Servicos, Carro, CategoriaManutencao
from django import forms

class ServicosForm(forms.ModelForm):
    class Meta:
        model = Servicos
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Verifica se o cliente está definido na instância
        if self.instance and self.instance.cliente:
            # Filtra os carros associados ao cliente
            self.fields['carro'].queryset = Carro.objects.filter(cliente=self.instance.cliente)
        else:
            # Exibe nenhum carro caso o cliente não esteja definido
            self.fields['carro'].queryset = Carro.objects.none()

class FormServico(ModelForm):
    class Meta:
        model = Servicos
        fields = "__all__"

servicos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .commands import ProcessaServicos, EnviaEmail
from django.contrib import messages 
from .models import Servicos, CategoriaManutencao


def novo_servico(request):
    if request.method == 'GET':
        clientes_obj, categorias_obj = ProcessaServicos(request).retorna_obj()
        return render(request, 'novo_servico.html', {
            'clientes': clientes_obj,
            'categorias': categorias_obj
        })

    elif request.method == 'POST':
        processa_servicos = ProcessaServicos(request)

        if processa_servicos.valida_ids():
            if processa_servicos.valida_estoque():  # Valida o estoque antes de salvar o serviço
                servico = processa_servicos.salva_servico()  # Cria e salva a instância do serviço
                processa_servicos.processa_estoque()  # Processa o estoque
                processa_servicos.associa_categorias(servico)  # Passa a instância do serviço

                if processa_servicos.erro_msg:
                    messages.error(request, processa_servicos.erro_msg)
                else:
                    messages.success(request, "Serviço adicionado com sucesso!")
                return redirect('servico', servico.protocolo)
            else:
                messages.error(request, processa_servicos.erro_msg)
                return render(request, 'novo_servico.html')
        else:
            messages.error(request, processa_servicos.erro_msg)
            return render(request, 'novo_servico.html')

def editar_servico(request):
    lista_servicos = Servicos.objects.all()
    if request.method == 'GET':
        return render(request, 'editar_servico.html', {'dados': {'servicos': lista_servicos}})

    elif request.method == 'POST':
        servico_id = request.POST.get('servico_id')
        protocolo = request.POST.get('protocolo')
        titulo_servico = request.POST.get('servico')
        mecanico = request.POST.get('mecanico')

        categorias = request.POST.getlist('categorias')
        valor_mao_de_obra = request.POST.getlist('valor_mao_de_obra')
        quantidade = request.POST.getlist('quantidades')

        data_inicio = request.POST.get('data_inicio')
        data_entrega = request.POST.get('data_entrega')

        validacao, servico_editado = ProcessaServicos.edita_servico(servico_id, titulo_servico, mecanico, categorias, valor_mao_de_obra, quantidade, data_inicio, data_entrega)

        if not validacao:
            messages.error(request, servico_editado)
            return render(request, 'editar_servico.html', {'dados': {'servicos': lista_servicos}}) 
        else:
            if servico_editado:
                messages.error(request, servico_editado)
                return redirect('servico', protocolo)
            else:
                messages.success(request, "Serviço modificado com sucesso!")
            return redirect('servico', protocolo)
    
    else:
        return redirect('editar_servico')

def seleciona_servico(request):
    if request.method == 'GET':
        return redirect('novo_servico')
    else:
        servico_id = request.POST.get('servico_selecionado')
        servico = get_object_or_404(Servicos, id=servico_id)
        
        dados = {
            'id': servico_id,
            'protocolo': servico.protocolo,
            'titulo': servico.titulo,
            'nome': servico.cliente.nome,
            'sobrenome': servico.cliente.sobrenome,
            'carro': servico.carro.carro,
            'placa': servico.carro.placa,
            'categoria': servico.categoria_manutencao.all(),
            'relacao': servico.servicocategoriaquantidade_set.all(),
            'categorias_existentes': CategoriaManutencao.objects.all(),
            'servicos': Servicos.objects.all(),
            'mecanico_responsavel': servico.mecanico_resp,
            'data_inicio': servico.data_inicio,
            'data_entrega': servico.data_entrega,
        }
            
        return render(request, 'editar_servico.html', {'dados': dados})


def listar_servico(request):
    if request.method == 'GET':
        servicos = Servicos.objects.all()
        return render(request, 'lista_servico.html', {'servicos': servicos})
    else:
        return redirect('listar_servico')


def protocolo(request, protocolo):
    if request.method == 'GET':
        servicos = get_object_or_404(Servicos, protocolo=protocolo)
        return render(request, 'servico.html', {'servico': servicos})
    else:
        return redirect('listar_servico')


def alterar_servico(request, servico_id):
    if request.method == 'POST':
        processa_servico = ProcessaServicos(request)
        protocolo = processa_servico.muda_status_servico(servico_id)

        messages.success(request, "Serviço atualizado com sucesso!")

        envia_email = EnviaEmail()
        envia_email.trata_emails(servico_id)
        
        return redirect('servico', protocolo) 

    return redirect('listar_servico') 


def carros_por_cliente(request, cliente_id):
    processa_servicos = ProcessaServicos(request)
    
    return processa_servicos.busca_carros_por_cliente(cliente_id)

servicos/templates/editar_servico.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}
Atualizar Serviço | AutoSync
{% endblock %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'servicos/css/editar_servico.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

{% endblock %}

{% block 'dashboard' %}
<br>
<div class="container">
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row mb-4">
        <div class="col-md-6">
            <a href="{% url 'novo_servico' %}">
                <div class="card-dashboard">
                    <p class="text-card">Adicionar Serviço</p>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'editar_servico' %}">
                <div class="card-dashboard">
                    <p class="text-card">Editar Serviço</p>
                </div>
            </a>
        </div>
        <div class="col-md">
            <a href="{% url 'listar_servico' %}" target="_blank">
                <div class="card-dashboard">
                    <p class="text-card">Listar Serviços</p>
                </div>
            </a>
        </div>
    </div>

    <div class="editar_servico">
        <form action='{% url "seleciona_servico" %}' method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-11">
                    <p>Selecione um serviço:</p>
                    <select id="servico_selecionado" name="servico_selecionado" class="form-control select-servico" required>
                        <option value="" disabled selected>Selecione um serviço</option>
                        {% for servico in dados.servicos %}
                        <option value="{{ servico.id }}">{{ servico.titulo }} | {{ servico.protocolo }} | {{ servico.cliente }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-1">
                    <p>Ação:</p>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            </div>
        </form>
        <br>

        {% if dados.relacao %}
        <form action="{% url 'editar_servico' %}" method="POST">
            <input type="hidden" name="servico_id" value="{{ dados.id }}">
            <input type="hidden" name="protocolo" value="{{ dados.protocolo }}">
            {% csrf_token %}
            <div class="row">
                <!-- Cliente -->
                <div class="col-md-6 form-group">
                    <label>Cliente:</label>
                    <input disabled name="cliente" type="text" value="{{ dados.nome }} {{ dados.sobrenome }}" class="form-control cliente">
                </div>

                <!-- Veiculo -->
                <div class="col-md-6 form-group">
                    <label>Veículo:</label>
                    <input disabled name="veiculo" type="text" value="{{ dados.carro }} | {{ dados.placa }}" class="form-control veiculo">
                </div>

                <!-- Título do Serviço -->
                <div class="col-md-6 form-group">
                    <label>Título do Serviço:</label>
                    <input name="servico" type="text" value="{{ dados.titulo }}" class="form-control">
                </div>
                <div class="col-md-6 form-group">
                    <label>Mecânico Responsável:</label>
                    <input name="mecanico" type="text" value="{{ dados.mecanico_responsavel|default:'-' }}"class="form-control">
                </div>
                <div class="col-md-12 form-group">
                    <label for="categorias">Serviços:</label>
                    <div id="categorias-container">
                        {% for categoria in dados.relacao %}
                            <div class="row mb-2 categoria-row">
                                <div class="col-md-6">
                                    <select name="categorias" id='categorias' class="form-control" required>
                                        <option value="{{categoria.categoria.id}}" selected>{{ categoria.categoria }}</option>
                                            {% for categorias_exist in dados.categorias_existentes %}
                                                <option value="{{ categorias_exist.id }}">{{ categorias_exist.titulo }}</option>
                                            {% endfor %}
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <input type="text" name="valor_mao_de_obra" value="{{categoria.valor_mao_de_obra}}" class="form-control" placeholder="Valor do Serviço">
                                </div>
                                <div class="col-md-2">
                                    <input type="number" name="quantidades" value="{{categoria.quantidade}}" class="form-control" placeholder="Quantidade" min="1" required>
                                </div>
                                <div class="col-md-1">
                                    <button type="button" class="btn btn-danger" onclick="remover_servico()">Excluir</button>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <button type="button" id="add-categoria" class="btn btn-primary mt-2">Adicionar Serviço</button>
                    </div>
                <!-- Data Início -->
                <div class="col-md-6 form-group">
                    <label>Data Início:</label>
                    <input name="data_inicio" value="{{ dados.data_inicio|date:'Y-m-d' }}" type="date" class="form-control" required>
                </div>
                <!-- Data Entrega -->
                <div class="col-md-6 form-group">
                    <label>Data Entrega:</label>
                    <input name="data_entrega" value="{{ dados.data_entrega|date:'Y-m-d' }}" type="date" class="form-control" required>
                </div>
                <div class="col-md-6">
                    <input type="submit" value="Confirmar Edição!" class="btn btn-success">
                </div>
            </div>
            <br>
        </form>
        {% endif %}
        
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'servicos/js/editar_servico.js' %}"></script>
{% endblock %}


<!-- 
        <p>{{ dados.servicos }}</p>
        <p>{{dados}}</p>
        <p>{{dados.relacao}}</p>
        {% for categoria in dados.relacao %}
            <p>Categoria:</p>
            <p>{{categoria}}</p>
            <p>Qtd</p>
            <p>{{categoria.quantidade}}</p>
            <p>Mao de obra</p>
            <p>{{categoria.valor_mao_de_obra}}</p>
        {% endfor %} -->

servicos/templates/lista_servico.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}
Listagem de Serviços | AutoSync
{% endblock %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'servicos/css/listar_servico.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css"> -->
{% endblock %}

{% block 'dashboard' %}
<div class="container-fluid distanciamento">
    <div class="cabecalho">
        <h3>Serviços:</h3>
    </div>
    <!-- <div class="row mb-3">
        <div class="col-12 d-flex justify-content-end"> 
            <div class="input-group" style="max-width: 300px;"> 
                <span class="input-group-text">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </span>
                <input 
                    type="text" 
                    id="searchInput" 
                    class="form-control text-start" 
                    placeholder="O que deseja buscar?">
            </div>
        </div>
    </div> -->
    
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Protocolo</th>
            <th scope="col">Titulo do Serviço</th>
            <th scope="col">Mecânico Responsável</th>
            <th scope="col">Cliente</th>
            <th scope="col">Data de Inicio</th>
            <th scope="col">Data de Entrega</th>
            <th scope="col">Status</th>
            <th scope="col">Preço Total</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for servico in servicos %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'servico' servico.protocolo %}" target="_blank" class="badge badge-dark protocolo">{{ servico.protocolo }}</a>
                    </th>                    
                    <td>{{servico.titulo}}</td>
                    <td>{{servico.mecanico_resp|default:"-"}}</td>
                    <td>{{servico.cliente}}</td>
                    <td>{{servico.data_inicio|date:"d/m/Y"}}</td>
                    {% if servico.data_entrega < data_atual and servico.status != 'Finalizado' and servico.status != 'Orçamento Reprovado'%}
                        <td><span class="atrasado">{{servico.data_entrega|date:"d/m/Y"}}</span></td>
                    {% else %}
                        <td>{{servico.data_entrega|date:"d/m/Y"}}</td>
                    {% endif %}
                    <td>
                        {% if servico.status == 'Em Orçamento' %}
                            <span class="badge badge-info">Em Orçamento</span>
                        {% elif servico.status == 'Orçamento Reprovado' %}
                            <span class="badge badge-danger">Orçamento Reprovado</span>
                        {% elif servico.status == 'Em Andamento' %}
                            <span class="badge badge-warning">Em Andamento</span>
                        {% else %}
                            <span class="badge badge-success">Finalizado</span>
                        {% endif %}
                    </td>
                    <td>{{servico.preco_total}}</td>
                </tr>
            {% endfor %}
        </tbody>
      </table>

</div>
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<!-- <script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script> -->
<script src="{% static 'servicos/js/lista_servico.js' %}"></script>
{% endblock %}

servicos/templates/novo_servico.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}
Novo Serviço | AutoSync
{% endblock %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'servicos/css/novo_servico.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    {% endblock %}
    
    {% block 'dashboard' %}
    <br>
    <div class="container">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    <div class="row mb-4">
        <div class="col-md-6">
            <a href="{% url 'novo_servico' %}">
                <div class="card-dashboard">
                    <p class="text-card">Adicionar Serviço</p>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'editar_servico' %}">
                <div class="card-dashboard">
                    <p class="text-card">Editar Serviço</p>
                </div>
            </a>
        </div>
        <div class="col-md">
            <a href="{% url 'listar_servico' %}" target="_blank">
                <div class="card-dashboard">
                    <p class="text-card">Listar Serviços</p>
                </div>
            </a>
        </div>
    </div>
    
    <div class="adicionar_servico">
        <form action='{% url "novo_servico" %}' method="POST">
            {% csrf_token %}
            <div class="row">
                <!-- Cliente -->
                <div class="col-md-6 form-group">
                    <label for="id_cliente">Cliente:</label>
                    <select id="id_cliente" name="cliente" class="form-control select-cliente" required>
                        <option value="" disabled selected>Selecione um cliente</option>
                        {% for cliente in clientes %}
                        <option value="{{ cliente.id }}">{{ cliente.nome }} {{ cliente.sobrenome }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Carro -->
                <div class="col-md-6 form-group">
                    <label for="id_carro">Veículo:</label>
                    <select id="id_carro" name="carro" class="form-control" required>
                        <option value="" disabled selected>Selecione um Veículo</option>
                    </select>
                </div>

                <!-- Título do Serviço -->
                <div class="col-md-6 form-group">
                    <label for="titulo_servico">Título do Serviço:</label>
                    <input id="titulo_servico" name="titulo_servico" type="text" class="form-control" required>
                </div>
                <div class="col-md-6 form-group">
                    <label for="titulo_servico">Notificar o Cliente Quando Finalizado?</label>
                    <select name="notificar" id="Notificar" class="form-control">
                        <option value="True">Sim</option>
                        <option value="False">Não</option>
                    </select>
                </div>
                
                <div class="col-md-12 form-group">
                    <label for="data_inicio">Mecânico Responsável:</label>
                    <input id="mecanico_responsavel" name="mecanico_responsavel" type="text" class="form-control">
                </div>
                <div class="col-md-12 form-group">
                    <label for="categorias">Serviços:</label>
                    <div id="categorias-container">
                        <div class="row mb-2 categoria-row">
                            <div class="col-md-6">
                                <select name="categorias" id='categorias' class="form-control" required>
                                    <option value="" disabled selected>Selecione um serviço</option>
                                        {% for categoria in categorias %}
                                            <option value="{{ categoria.id }}">{{ categoria.titulo }}</option>
                                        {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-3">
                                <input type="number" name="valor_mao_de_obra" class="form-control" placeholder="Valor do Serviço"  step="0.01" min="0">
                            </div>
                            <div class="col-md-2">
                                <input type="number" name="quantidades" class="form-control" placeholder="Quantidade" min="1" required>
                            </div>
                            <div class="col-md-1">
                                <button type="button" class="btn btn-danger" onclick="remover_servico(event)">Excluir</button>
                            </div>
                        </div>
                    </div>
                    <button type="button" id="add-categoria" class="btn btn-primary mt-2">Adicionar Serviço</button>
                </div>
                
                <!-- Data Início -->
                <div class="col-md-6 form-group">
                    <label for="data_inicio">Data Início:</label>
                    <input id="data_inicio" name="data_inicio" type="date" class="form-control" required>
                </div>

                <!-- Data Entrega -->
                <div class="col-md-6 form-group">
                    <label for="data_entrega">Data Entrega:</label>
                    <input id="data_entrega" name="data_entrega" type="date" class="form-control" required>
                </div>
            </div>
            <br>
            <input type="submit" value="Cadastrar" class="btn btn-success">
        </form>
        <br>

        <br>
    </div>
</div>

{% endblock %}

{% block 'body' %}
<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'servicos/js/novo_servico.js' %}"></script>
{% endblock %}